name: CI

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
     
      - 'kubernetes/**'
      - 'README.md'
jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15   # ŸÑŸà MySQL ÿ∫ŸäŸëÿ±Ÿáÿß ŸÑŸÄ mysql:8
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: appdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d appdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # üöÄ 1. Build & Test Go Backend
      # ----------------------------
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Go Dependencies
        run: go mod download
        working-directory: ./auth   # ‚Üê ŸÖÿ¨ŸÑÿØ ÿßŸÑŸÄ backend

      - name: Run Go Tests
        run: go test ./...
        working-directory: ./auth

      # ----------------------------
      # üé® 2. Build & Test Node.js UI
      # ----------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3Ô∏è‚É£ Install validator dependencies
      - name: Install dependencies
        run: |
          npm install -g ajv-cli jsonlint

      # 4Ô∏è‚É£ Check JSON syntax
      - name: Lint all JSON files
        run: |
          find data -name "*.json" -print0 | xargs -0 jsonlint -q


    
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 3Ô∏è‚É£ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          pip install flake8 black bandit pytest

      # 4Ô∏è‚É£ Run Linter (Flake8)
      - name: Run Flake8
        run:  |
         flake8 ./weather
         if [ $? -ne 0 ]; then
          echo "Flake8 found issues!"
          exit 1
         fi
        

      # 5Ô∏è‚É£ Run Code Formatter Check (Black)
      - name: Run Black
        # if: failure ()
        if: steps.flake8.outcome == 'failure'
        run: black  ./weather
        
        
        

      # 6Ô∏è‚É£ Run Security Scan (Bandit)
      - name: Run Bandit
        run: bandit -r ./weather

      # # 7Ô∏è‚É£ Run Unit Tests
      # - name: Run Tests
      #   run: pytest
  code-quality:
    runs-on: ubuntu-latest
    needs: build-test


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: Mushus/golangci-linter@v1
    - name: Rub action json code quality
      uses: actions/checkout@v2
    - name: run python code code-quality
      uses: ricardochaves/python-lint@v1.4.0
   
  push:
    runs-on: ubuntu-latest

    needs: 
    - build-test
    - code-quality

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action Data_Base
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./k8s-course-lab-main/UI/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/DataBase:${{github.run_id}}
    
    - name: Build and Push action Authentication
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./k8s-course-lab-main/auth/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/Auth:${{github.run_id}}
    - name: Build and Push action authentication
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./k8s-course-lab-main/auth/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth:${{github.run_id}}
    
      
     
    - name: Build and Push action weather
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./k8s-course-lab-main/weather/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/Weather:${{github.run_id}}
    
      